Force disconnect on start with qemu-nbd if ssh access is not set and add ./tools/tool_cef_functions

diff --git a/tools/tool_functions b/tools/tool_functions
--- a/tools/tool_functions
+++ b/tools/tool_functions
@@ -239,41 +239,115 @@ function handleErrorsCodes()
   local code=$1
   local source=$2
   local label=$3
+  local console=$4
+  local exit_on_err=$5
+  local startString;
+  local endString;
+
   if [ $code = 0 ];then
     return;fi
 
-  local error="<b>Unknown error occoured for check of '$label'</b>"
+  if [ -z $console ];then
+    startString="<b>";
+    endString="</b>";
+  fi
 
-  if [[ $source = sshpass ]];then
+  local error="${startString}Unknown error occoured for check of '$label'${endString}"
+  if [[ $source = unzip ]];then
     if [[ $code = 1 ]];then
-      error="<b>The '$label' have invalid command line argument</b>"
+      error="${startString}The '$label' have \
+one or more warning errors were encountered, but processing completed successfully anyway. This includes zip‐\
+files where one or more files was skipped due to unsupported compression method or encryption with an unknown \
+password.${endString}"
     elif [[ $code = 2 ]];then
-      error="<b>The '$label' have conflicting arguments given</b>"
+      error="${startString}The '$label' have \
+a generic error in the zipfile format was detected. Processing may have completed successfully anyway; some \
+broken zipfiles created by other archivers have simple work-arounds.${endString}"
     elif [[ $code = 3 ]];then
-      error="<b>The '$label' have general runtime error</b>"
+      error="${startString}The '$label' have a severe error in the zipfile format was detected.  Processing probably failed immediately.${endString}"
     elif [[ $code = 4 ]];then
-      error="<b>The '$label' have unrecognized response from ssh (parse error)</b>"
+      error="${startString}On '$label' unzip was unable to allocate memory for one or more buffers during program initialization.${endString}"
     elif [[ $code = 5 ]];then
-      error="<b>The '$label' have invalid/incorrect password</b>"
+      error="${startString}On '$label' unzip was unable to allocate memory or unable to obtain a tty to read the decryption password(s).${endString}"
     elif [[ $code = 6 ]];then
-      error="<b>Host public key for '$label' is unknown. exits without confirming the new key.</b>"
+      error="${startString}On '$label' unzip was unable to allocate memory during decompression to disk.${endString}"
+    elif [[ $code = 7 ]];then
+      error="${startString}On '$label' unzip was unable to allocate memory during in-memory decompression.${endString}"
+    elif [[ $code = 8 ]];then
+      error="${startString}The '$label' have [currently not used]${endString}"
+    elif [[ $code = 9 ]];then
+      error="${startString}The '$label' have the specified zipfiles were not found.${endString}"
+    elif [[ $code = 10 ]];then
+      error="${startString}The '$label' have invalid options were specified on the command line.${endString}"
+    elif [[ $code = 11 ]];then
+      error="${startString}The '$label' have no matching files were found.${endString}"
+    elif [[ $code = 50 ]];then
+      error="${startString}The '$label' have the disk is (or was) full during extraction.${endString}"
+    elif [[ $code = 51 ]];then
+      error="${startString}The '$label' have the end of the ZIP archive was encountered prematurely.${endString}"
+    elif [[ $code = 80 ]];then
+      error="${startString}The '$label' have the user aborted unzip prematurely with control-C (or similar)${endString}"
+    elif [[ $code = 81 ]];then
+      error="${startString}The '$label' have testing or extraction of one or more files failed due to unsupported compression methods or unsupported decryption.${endString}"
+    elif [[ $code = 82 ]];then
+      error="${startString}On '$label' no files were found due to bad decryption password(s). (If even one file is successfully processed, however, the exit status is 1.)${endString}"
+    fi
+  elif [[ $source = wget ]];then
+    if [[ $code = 1 ]];then
+      error="${startString}The '$label' have generic error code.${endString}"
+    elif [[ $code = 2 ]];then
+      error="${startString}The '$label' have parse error---for instance, when parsing command-line options, the .wgetrc or .netrc...${endString}"
+    elif [[ $code = 3 ]];then
+      error="${startString}The '$label' have file I/O error.${endString}"
+    elif [[ $code = 4 ]];then
+      error="${startString}The '$label' have network failure.${endString}"
+    elif [[ $code = 5 ]];then
+      error="${startString}The '$label' have SSL verification failure.${endString}"
+    elif [[ $code = 6 ]];then
+      error="${startString}The '$label' have username/password authentication failure.${endString}"
+    elif [[ $code = 7 ]];then
+      error="${startString}The '$label' have protocol errors.${endString}"
+    elif [[ $code = 8 ]];then
+      error="${startString}The '$label' have server issued an error response.${endString}"
+    fi
+  elif [[ $source = sshpass ]];then
+    if [[ $code = 1 ]];then
+      error="${startString}The '$label' have invalid command line argument${endString}"
+    elif [[ $code = 2 ]];then
+      error="${startString}The '$label' have conflicting arguments given${endString}"
+    elif [[ $code = 3 ]];then
+      error="${startString}The '$label' have general runtime error${endString}"
+    elif [[ $code = 4 ]];then
+      error="${startString}The '$label' have unrecognized response from ssh (parse error)${endString}"
+    elif [[ $code = 5 ]];then
+      error="${startString}The '$label' have invalid/incorrect password${endString}"
+    elif [[ $code = 6 ]];then
+      error="${startString}Host public key for '$label' is unknown. exits without confirming the new key.${endString}"
     elif [[ $code = 255 ]];then
-      error="\<b>
+      error="\${startString}
 Connection to '$label' was not possible!
 
-Is the related source running and have SSH access enabled?</b>"
+Is the related source running and have SSH access enabled?${endString}"
     fi
   elif [[ $source = git ]];then
     if [[ $code = 128 ]];then
-      error="<b>\
+      error="${startString}\
 The '$label' does not appear to be a git repository
 Could not read from remote repository.
 
 Please make sure you have the correct access rights
-and the repository exists.</b>"
+and the repository exists.${endString}"
     fi
   fi
-  showErrorDialog "$error"
+
+  if [ -z $console ];then
+    showErrorDialog "$error"
+  else
+    printf "\n${RED}${BRIGHT}Error: ${WHITE}${source} - ${error}${NORMAL}\n";fi
+
+  if [ ! -z $exit_on_err ];then
+    exit 1;
+  fi
 }
 ##
 
